### ISSUE TITLE
请教训练流程、命令

### ISSUE THREAD

**Issue by yeqingQian** [Leosocy/EDCC-Palmprint-Recognition#1]
你好，我想请教一下，您的算法是如何训练的，采用的是CNN方面吗？
还有我在linux上调试的时候无法生成lib相关文件，整个流程您可以大概在跟我说一下吗？谢谢

**Comment by Leosocy** [comment]
没有那么高端啦，没用机器学习的算法，是比较纯粹的图像处理和掌纹竞争编码算法。主要提供了三个api，第一个是提取掌纹的特征，第二个是两个掌纹特征比较获取相似度，第三个是两幅掌纹图像直接比较获取相似度。主要用法在include下面的README有说明。另外，如果使用python的话，samples目录下面有一个python调用接口的例子，可以参考一下。
ps：Linux不能执行，这个我抽空搞一下。
pps：如果你想用机器学习搞得话，可以带带我，我对CNN，RNN也很感兴趣。

**Comment by yeqingQian** [comment]
哦哦，好的，谢谢你。
那您这边的是调用相应api来实现的？那是不是说是不用训练只要计算两幅图像之间的相似度就可以了？
那您是如何训练的呢？
CNN这块我也才开始搞，感觉文献少还弄不明白

**Comment by Leosocy** [comment]
是的，不考虑建立数据库的话，可以直接调用比较两幅图像的掌纹相似度即可。
不需要训练，直接提取的是掌纹的特征，利用特征比较的。具体算法原理可以看我的GitHub Pages。

**Comment by yeqingQian** [comment]
哦哦，好的，谢谢你哦，
