### ISSUE TITLE
No module named 'edcc_adapter'

### ISSUE THREAD

**Issue by qymspace** [Leosocy/EDCC-Palmprint-Recognition#12]
After installing the project successfully. I can't import the module

**Comment by Leosocy** [comment]
> After installing the project successfully. I can't import the module

Can you show me the installation log when you run `sudo make install`

**Comment by qymspace** [comment]
I created a new python virtual environment with python 3, re-cloned this repo and installed and now works seamlessly..Could you please point me in the right direction regards processing of raw images from a camera to point that they can be compared correctly using the library. The accuracy of raw images from the camera is quite low.

**Comment by Leosocy** [comment]
> I created a new python virtual environment with python 3, re-cloned this repo and installed and now works seamlessly..Could you please point me in the right direction regards processing of raw images from a camera to point that they can be compared correctly using the library. The accuracy of raw images from the camera is quite low.

I think you *can't* use original raw images from the camera unless you preprocess them and get the `ROI` of palm iamge. The `EDCC` algorithm only achieve high accuracy when recognize `ROI`.

I have another project called  [`RobustPalmRoi`](https://github.com/Leosocy/RobustPalmRoi) which is an algorithm to extract the ROI of palm image in complex environment.

**Comment by qymspace** [comment]
Okay thank you. Lemme close these.
