### ISSUE TITLE
error of Building CXX object CMakeFiles/edcc.dir/src/core/gabor_filter.cpp.o

### ISSUE THREAD

**Issue by edwardLui** [Leosocy/EDCC-Palmprint-Recognition#15]
i have a error when i build the edcc
[ 14%] Building CXX object CMakeFiles/edcc.dir/src/core/gabor_filter.cpp.o
/Users/edward/Documents/COMP4134/comp4134 project/EDCC-Palmprint-Recognition-master/EDCC-Palmprint-Recognition/src/core/gabor_filter.cpp:54:30: error: use of undeclared identifier 'CV_BGR2GRAY'
  cvtColor(resized, *result, CV_BGR2GRAY);
                             ^
1 error generated.
make[2]: *** [CMakeFiles/edcc.dir/src/core/gabor_filter.cpp.o] Error 1
make[1]: *** [CMakeFiles/edcc.dir/all] Error 2
make: *** [all] Error 2

**Comment by Leosocy** [comment]
> i have a error when i build the edcc
> [ 14%] Building CXX object CMakeFiles/edcc.dir/src/core/gabor_filter.cpp.o
> /Users/edward/Documents/COMP4134/comp4134 project/EDCC-Palmprint-Recognition-master/EDCC-Palmprint-Recognition/src/core/gabor_filter.cpp:54:30: error: use of undeclared identifier 'CV_BGR2GRAY'
> cvtColor(resized, *result, CV_BGR2GRAY);
> ^
> 1 error generated.
> make[2]: *** [CMakeFiles/edcc.dir/src/core/gabor_filter.cpp.o] Error 1
> make[1]: *** [CMakeFiles/edcc.dir/all] Error 2
> make: *** [all] Error 2

It happens because consts variable like `CV_` have changed in opencv 3.0. I have fixed this issuse, please pull for latest code and build again.

**Comment by edward95914** [comment]
I run the example.py, it raise FileNotFoundError

Traceback (most recent call last):
  File "/Users/edward/Documents/COMP4134/comp4134 project/EDCC-Palmprint-Recognition-master/examples/py_example/example.py", line 18, in <module>
    one_palmprint_code = encoder.encode_using_file(TEST_A_01_PALMPRINT_IMAGE)
  File "/Users/edward/Documents/COMP4134/comp4134 project/venv/lib/python3.6/site-packages/edcc-0.2.0-py3.6.egg/edcc/encoder.py", line 19, in encode_using_file
FileNotFoundError: [Errno 2] No such file or directory: '../palmprint_dataalmprint_data/a_01.bmp'

**Comment by Leosocy** [comment]
> I run the example.py, it raise FileNotFoundError
> 
> Traceback (most recent call last):
> File "/Users/edward/Documents/COMP4134/comp4134 project/EDCC-Palmprint-Recognition-master/examples/py_example/example.py", line 18, in 
> one_palmprint_code = encoder.encode_using_file(TEST_A_01_PALMPRINT_IMAGE)
> File "/Users/edward/Documents/COMP4134/comp4134 project/venv/lib/python3.6/site-packages/edcc-0.2.0-py3.6.egg/edcc/encoder.py", line 19, in encode_using_file
> FileNotFoundError: [Errno 2] No such file or directory: '../palmprint_dataalmprint_data/a_01.bmp'

It looks like you didn't download the example images. You can enter `palmprint_data` directory, and run `sh download.sh`, then run py example again.
