### ISSUE TITLE
请教参数选择

### ISSUE THREAD

**Issue by Jun-jie-Huang** [Leosocy/EDCC-Palmprint-Recognition#17]
您好，最近看到您的写的算法教程，我自己实现了一个，但是目前准确率只有67%，可能是我参数选择有些问题，想请问下关于gabor filter和拉普拉斯算子的参数是设的多少？

**Comment by Leosocy** [comment]
> 您好，最近看到您的写的算法教程，我自己实现了一个，但是目前准确率只有67%，可能是我参数选择有些问题，想请问下关于gabor filter和拉普拉斯算子的参数是设的多少？

抱歉才看到issue，可以参照[python例子里面的配置](https://github.com/Leosocy/EDCC-Palmprint-Recognition/blob/master/examples/py_example/example.py#L16)，[参数对应关系](https://github.com/Leosocy/EDCC-Palmprint-Recognition/blob/master/pypackage/edcc/config.py#L10)
