### ISSUE TITLE
error when python setup.py install

### ISSUE THREAD

**Issue by manoharsonwan** [Leosocy/EDCC-Palmprint-Recognition#18]
This is the error I got while running python seytup.py install
and also same kind of error on Robustpalmroi

Traceback (most recent call last):
  File "/home/qwickbit/Desktop/EDCC-Palmprint-Recognition/pypackage/edcc/adapter.py", line 24, in __init__
    self._lib = ctypes.cdll.LoadLibrary(self.LIB_NAME)
  File "/home/qwickbit/anaconda3/lib/python3.6/ctypes/__init__.py", line 426, in LoadLibrary
    return self._dlltype(name)
  File "/home/qwickbit/anaconda3/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libedcc.so: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 10, in <module>
    import edcc
  File "/home/qwickbit/Desktop/EDCC-Palmprint-Recognition/pypackage/edcc/__init__.py", line 31, in <module>
    adapter = EdccAdapter()
  File "/home/qwickbit/Desktop/EDCC-Palmprint-Recognition/pypackage/edcc/adapter.py", line 28, in __init__
    self.LIB_NAME, self.LIB_INSTALLATION_URL
OSError: Library [libedcc.so] not found.
Please see https://github.com/Leosocy/EDCC-Palmprint-Recognition#install-library

**Comment by Leosocy** [comment]
> This is the error I got while running python seytup.py install
> and also same kind of error on Robustpalmroi
> 
> Traceback (most recent call last):
> File "/home/qwickbit/Desktop/EDCC-Palmprint-Recognition/pypackage/edcc/adapter.py", line 24, in **init**
> self._lib = ctypes.cdll.LoadLibrary(self.LIB_NAME)
> File "/home/qwickbit/anaconda3/lib/python3.6/ctypes/**init**.py", line 426, in LoadLibrary
> return self._dlltype(name)
> File "/home/qwickbit/anaconda3/lib/python3.6/ctypes/**init**.py", line 348, in **init**
> self._handle = _dlopen(self._name, mode)
> OSError: libedcc.so: cannot open shared object file: No such file or directory
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "setup.py", line 10, in 
> import edcc
> File "/home/qwickbit/Desktop/EDCC-Palmprint-Recognition/pypackage/edcc/**init**.py", line 31, in 
> adapter = EdccAdapter()
> File "/home/qwickbit/Desktop/EDCC-Palmprint-Recognition/pypackage/edcc/adapter.py", line 28, in **init**
> self.LIB_NAME, self.LIB_INSTALLATION_URL
> OSError: Library [libedcc.so] not found.
> Please see https://github.com/Leosocy/EDCC-Palmprint-Recognition#install-library

Do you have `so library` installed?

**Comment by manoharsonwan** [comment]
I solved this issue 

> > This is the error I got while running python seytup.py install
> > and also same kind of error on Robustpalmroi
> > Traceback (most recent call last):
> > File "/home/qwickbit/Desktop/EDCC-Palmprint-Recognition/pypackage/edcc/adapter.py", line 24, in **init**
> > self._lib = ctypes.cdll.LoadLibrary(self.LIB_NAME)
> > File "/home/qwickbit/anaconda3/lib/python3.6/ctypes/**init**.py", line 426, in LoadLibrary
> > return self._dlltype(name)
> > File "/home/qwickbit/anaconda3/lib/python3.6/ctypes/**init**.py", line 348, in **init**
> > self._handle = _dlopen(self._name, mode)
> > OSError: libedcc.so: cannot open shared object file: No such file or directory
> > During handling of the above exception, another exception occurred:
> > Traceback (most recent call last):
> > File "setup.py", line 10, in
> > import edcc
> > File "/home/qwickbit/Desktop/EDCC-Palmprint-Recognition/pypackage/edcc/**init**.py", line 31, in
> > adapter = EdccAdapter()
> > File "/home/qwickbit/Desktop/EDCC-Palmprint-Recognition/pypackage/edcc/adapter.py", line 28, in **init**
> > self.LIB_NAME, self.LIB_INSTALLATION_URL
> > OSError: Library [libedcc.so] not found.
> > Please see https://github.com/Leosocy/EDCC-Palmprint-Recognition#install-library
> 
> Do you have `so library` installed?

**Comment by manoharsonwan** [comment]
> I solved this issue
> 
> > > This is the error I got while running python seytup.py install
> > > and also same kind of error on Robustpalmroi
> > > Traceback (most recent call last):
> > > File "/home/qwickbit/Desktop/EDCC-Palmprint-Recognition/pypackage/edcc/adapter.py", line 24, in **init**
> > > self._lib = ctypes.cdll.LoadLibrary(self.LIB_NAME)
> > > File "/home/qwickbit/anaconda3/lib/python3.6/ctypes/**init**.py", line 426, in LoadLibrary
> > > return self._dlltype(name)
> > > File "/home/qwickbit/anaconda3/lib/python3.6/ctypes/**init**.py", line 348, in **init**
> > > self._handle = _dlopen(self._name, mode)
> > > OSError: libedcc.so: cannot open shared object file: No such file or directory
> > > During handling of the above exception, another exception occurred:
> > > Traceback (most recent call last):
> > > File "setup.py", line 10, in
> > > import edcc
> > > File "/home/qwickbit/Desktop/EDCC-Palmprint-Recognition/pypackage/edcc/**init**.py", line 31, in
> > > adapter = EdccAdapter()
> > > File "/home/qwickbit/Desktop/EDCC-Palmprint-Recognition/pypackage/edcc/adapter.py", line 28, in **init**
> > > self.LIB_NAME, self.LIB_INSTALLATION_URL
> > > OSError: Library [libedcc.so] not found.
> > > Please see https://github.com/Leosocy/EDCC-Palmprint-Recognition#install-library
> > 
> > 
> > Do you have `so library` installed?
I solved this issue but I am getting a new one  which is:


  File "example.py", line 16, in <module>
    config = edcc.EncoderConfig(29, 5, 5, 10)
AttributeError: module 'edcc' has no attribute 'EncoderConfig'

**Comment by tbfly** [comment]
try run 'ldconfig'

**Comment by tharakarehan** [comment]
> I solved this issue
> 
> > > This is the error I got while running python seytup.py install
> > > and also same kind of error on Robustpalmroi
> > > Traceback (most recent call last):
> > > File "/home/qwickbit/Desktop/EDCC-Palmprint-Recognition/pypackage/edcc/adapter.py", line 24, in **init**
> > > self._lib = ctypes.cdll.LoadLibrary(self.LIB_NAME)
> > > File "/home/qwickbit/anaconda3/lib/python3.6/ctypes/**init**.py", line 426, in LoadLibrary
> > > return self._dlltype(name)
> > > File "/home/qwickbit/anaconda3/lib/python3.6/ctypes/**init**.py", line 348, in **init**
> > > self._handle = _dlopen(self._name, mode)
> > > OSError: libedcc.so: cannot open shared object file: No such file or directory
> > > During handling of the above exception, another exception occurred:
> > > Traceback (most recent call last):
> > > File "setup.py", line 10, in
> > > import edcc
> > > File "/home/qwickbit/Desktop/EDCC-Palmprint-Recognition/pypackage/edcc/**init**.py", line 31, in
> > > adapter = EdccAdapter()
> > > File "/home/qwickbit/Desktop/EDCC-Palmprint-Recognition/pypackage/edcc/adapter.py", line 28, in **init**
> > > self.LIB_NAME, self.LIB_INSTALLATION_URL
> > > OSError: Library [libedcc.so] not found.
> > > Please see https://github.com/Leosocy/EDCC-Palmprint-Recognition#install-library
> > 
> > 
> > Do you have `so library` installed?

how did you solve this issue? I got the same

**Comment by JUZXF** [comment]
您好，我也遇到了一样的问题。我是基于windows系统下的anaconda创建的虚拟环境进行的编译，报了一样的错。请问需需要安装so library是啥？我这样的环境可以装吗
