### ISSUE TITLE
edcc has no attribute 'EncoderConfig'

### ISSUE THREAD

**Issue by manoharsonwan** [Leosocy/EDCC-Palmprint-Recognition#20]
I am getting this error while running the example.py file 

File "example.py", line 16, in 
config = edcc.EncoderConfig(29, 5, 5, 10)
AttributeError: module 'edcc' has no attribute 'EncoderConfig'

**Comment by Leosocy** [comment]
> I am getting this error while running the example.py file
> 
> File "example.py", line 16, in
> config = edcc.EncoderConfig(29, 5, 5, 10)
> AttributeError: module 'edcc' has no attribute 'EncoderConfig'

Reinstall pypackage and try again.
