### ISSUE TITLE
OSError: Library [libedcc.dylib] not found.

### ISSUE THREAD

**Issue by yuerunyu** [Leosocy/EDCC-Palmprint-Recognition#23]
Hello,
my system is MacOS,when I exectue command "python3 setup.py install",error"OSError: Library [libedcc.dylib] not found.",But the file (libedcc.dylib) is in the directory(build),so ,can someone help me ?

**Comment by Leosocy** [comment]
Did you ran `mkdir -p build && cd build
cmake .. && sudo make install`  command before `python3 setup.py install`?

**Comment by yuerunyu** [comment]
Yes,I have run command,Now,I have solve the problem,  thank you very much!
