### ISSUE TITLE
同类手掌的掌纹识别失败

### ISSUE THREAD

**Issue by JUZXF** [Leosocy/EDCC-Palmprint-Recognition#24]
您好：
同类手掌的掌纹也识别失败，，原因是待比对两张图片未校准，请问你有校准部分的代码吗？校准包括平移或者 旋转之类的；
望回复。谢谢

**Comment by Leosocy** [comment]
> 您好：
> 同类手掌的掌纹也识别失败，，原因是待比对两张图片未校准，请问你有校准部分的代码吗？校准包括平移或者 旋转之类的；
> 望回复。谢谢

可以试下我的这个项目 https://github.com/Leosocy/RobustPalmRoi
