### ISSUE TITLE
安装失败

### ISSUE THREAD

**Issue by huiqiTian222** [Leosocy/EDCC-Palmprint-Recognition#25]
您好，我是在Windows下装的，但是编译完发现没有edcc.lib 而且用dumpbin  到处edcc.dll 显示并没有函数，没有lib无法编译其他代码啊 ，求赐教

**Comment by Leosocy** [comment]
> 您好，我是在Windows下装的，但是编译完发现没有edcc.lib 而且用dumpbin 到处edcc.dll 显示并没有函数，没有lib无法编译其他代码啊 ，求赐教

不建议使用windows，编译根本没有支持win

**Comment by huiqiTian222** [comment]
这样啊，好的，谢谢
