### ISSUE TITLE
同一个人的掌纹相似度过低

### ISSUE THREAD

**Issue by zhouchaohong1111** [Leosocy/EDCC-Palmprint-Recognition#27]
./data/a_01.bmp <-> ./data/a_02.bmp similarity score:0.2390011890606421
./data/b_01.bmp <-> ./data/b_02.bmp similarity score:0.22711058263971462
demo 里边的数据的相似度 很低，是正常的吗？ 实际使用需要别的配置参数？

**Comment by Leosocy** [comment]
> ./data/a_01.bmp <-> ./data/a_02.bmp similarity score:0.2390011890606421
> ./data/b_01.bmp <-> ./data/b_02.bmp similarity score:0.22711058263971462
> demo 里边的数据的相似度 很低，是正常的吗？ 实际使用需要别的配置参数？

手掌图片有预处理过吗？有提取ROI吗？

**Comment by zhouchaohong1111** [comment]
上边的数据，是使用download.sh下载的你工程里边自带的图片，相似度也很低。我自己的掌纹是有预处理的，跟工程里大小差不多，对应区域也差不多，我自己的图片相似度更低，只有0.07-0.08。

**Comment by Leosocy** [comment]
> 上边的数据，是使用download.sh下载的你工程里边自带的图片，相似度也很低。我自己的掌纹是有预处理的，跟工程里大小差不多，对应区域也差不多，我自己的图片相似度更低，只有0.07-0.08。

这个是要相对去比的，会选取对比集中匹配得分最高的那张作为匹配结果。README里提到了匹配的算法。不是说相同手掌相似度就是80%以上。因为这个编码针对每一个掌纹像素点都做了编码，所以得分会比较低。
